name: Sync

on:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    
    - name: Update upstream repo
      working-directory: ./domain-list-community
      run: |
        git remote add upstream https://github.com/v2ray/domain-list-community.git
        git fetch upstream master
        git checkout upstream/master

    - name: Delete unused go files
      working-directory: ./domain-list-community
      run: |
        echo $PWD
        pwd
        ls
        rm -rf *.go *.mod *.sum

    - name: Generate
      working-directory: ./
      run: go run main.go

    - name: Reset upstream repo
      working-directory: ./domain-list-community
      run: |
        git reset --hard

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
